server:
  port: 8080

spring:
  config:
    import:
      - optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/students/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/courses/**

